/**
 * Proveedores permitidos en POST /api/purchases/bulk-upload.
 * Mantener alineado con: src/constants/bulkUploadAllowedSuppliers.ts
 */
export const BULK_UPLOAD_ALLOWED_SUPPLIERS = [
  'ACME / USA / PE USA',
  'AOI',
  'DIESEL',
  'DIESEL TRADING CO',
  'E&F / USA / PE USA',
  'EUROAUCTIONS',
  'EUROAUCTIONS / ESP',
  'EUROAUCTIONS / GER',
  'EUROAUCTIONS / UK',
  'GDF',
  'GOSHO',
  'GREEN',
  'GREENAUCT',
  'GREENAUCT / J&F',
  'GUIA',
  'HCMJ',
  'HCMJ / KANAMOTO',
  'HCMJ / ONAGA',
  'HITACHI',
  'HITACHI/ONAGA',
  'IRON PLANET',
  'IRON PLANET/ BOOM & BUCKET',
  'IRON PLANET/ BOOM & BUCKET / USA /PE USA',
  'IRON PLANET / USA / PE USA',
  'JEN',
  'JEN/TRANSFERIDO A ONAGA',
  'JTF',
  'JTF SHOJI',
  'KANEHARU',
  'KATAGIRI',
  'KIXNET',
  'MONJI',
  'MONJI/DIESEL',
  'MONJI/DIESEL TRADING CO',
  'MULTISERVICIOS / USA / PE USA',
  'NDT',
  'NDT / J&F',
  'NORI',
  'NORI/JEN',
  'ONAGA',
  'PQ USA / ACME',
  'PQ USA / MULTISERVICIOS',
  'PQ USA / RITCHIE BROS',
  'PQ USA / RITCHIE BROS CANADA',
  'PQ USA / ROYAL',
  'REIBRIDGE',
  'REIBRIDGE INC',
  'RITCHIE / CAN / PE USA',
  'RITCHIE / ESP',
  'RITCHIE / USA / PE USA',
  'ROYAL - PROXY / USA / PE USA',
  'SHOJI',
  'SOGO',
  'THI',
  'THI / J&F',
  'TOYOKAMI',
  'TOZAI',
  'WAKITA',
  'YIWU',
  'YIWU ELI / CHINA',
  'YIWU ELI TRADING COMPANY / CHINA',
  'YUASA',
  'YUMAC',
  'YUVASA',
];
