/** Lista de proveedores para el módulo "Nueva Compra" (NewPurchasesPage y PurchaseFormNew). */
export const NEW_PURCHASE_SUPPLIERS = [
  'HITACHI',
  'CASE',
  'YANMAR',
  'DYNAPAC',
  'LIUGONG',
  'AMMANN',
  'GREENAUCT / J&F',
  'JEN/TRANSFERIDO A ONAGA',
  'NDT / J&F',
  'NORI/JEN',
  'PQ USA / MULTISERVICIOS',
  'PQ USA / RITCHIE BROS',
  'PQ USA / RITCHIE BROS CANADA',
  'PQ USA / ROYAL',
  'REIBRIDGE INC',
  'THI / J&F',
  'CNHI International SA',
  'Hitachi Construction Machinery Americas Inc',
  'Dynapac do Brasil LTDA',
  'Yanmar Construction Equipment Co., Ltd',
  'Okada Aiyon Corporation',
  'Liugong Machinery Hongkong Co., Limited',
];
